### ISSUE TITLE
Unsure of need for cluster-admin / host networking

### ISSUE THREAD

**Issue by ghost** [aws-samples/aws-xray-kubernetes#7]
From looking at documentation, it doesn't look like the xray daemon needs cluster-admin permissions (or any kubernetes api access whatsoever) or host networking enabled. Is there anything I've missed or can those be safely removed from the manifest?

**Comment by ckassen** [comment]
Ideally this project would also be able to use something like IAM for Service Accounts to grant permissions to the daemon.

Any other set of permissions should not be required. Feel free to remove the code and send a PR.

**Comment by leeclark7878** [comment]
I've removed these as a test, works fine.

**Comment by ckassen** [comment]
I have removed the permissions and added instructions how to set up IAM Roles for Service Accounts to your EKS cluster (if you use the open source web hook this also works for k8s on EC2).

Thanks for the valuable input and ensuring this project sticks to best practices.
