### ISSUE TITLE
XRay Daemon routing issue

### ISSUE THREAD

**Issue by kwalczak** [aws-samples/aws-xray-kubernetes#9]
I tired to reproduce what was presented in [this](https://aws.amazon.com/blogs/compute/application-tracing-on-kubernetes-with-aws-x-ray/) blog post and at the first sight all seems to look ok. 

But after verification, I discovered, that when serviceA is accessing xray daemon it is doing it via kubernetes service - so it is loadballanced, and request can be routed to daemon deployed on other node than the application. 

So instead of this:
![](https://d2908q01vomqb2.cloudfront.net/1b6453892473a467d07372d45eb05abc2031647a/2018/02/28/xray-architecture-1024x589.jpeg)
It looks more like this: 
<img width="1279" alt="Zrzut ekranu 2020-05-15 o 15 47 45" src="https://user-images.githubusercontent.com/11299554/82058262-ce78c880-96c4-11ea-9e9b-623d970c5a65.png">

> When deploying the container using a DaemonSet, the X-Ray port is also exposed directly on the host. This way, clients can connect directly to the daemon on your node. This avoids unnecessary network traffic going across your cluster.

So my question is how to achieve this? How to connect to xray on same node.

**Comment by ckassen** [comment]
To optimize the security profile and simplify the deployment the host networking option has been removed. With the current setup any node can easily send traffic to the daemon.

If you'd like you can investigate NodePort and check if this simplifies the setup. Happy to review a PR.

**Comment by kwalczak** [comment]
So just to be clear:

Current go to setup is that x-ray daemon is exposed to application via k8s service - meaning you're not tight to your node's daemon and any other can be picked. Correct?

**Comment by ckassen** [comment]
@kwalczak yes, that is correct. I'd have to think about changing from `DaemonSet` to a regular `Deployment` to avoid running too many X-Ray daemons.
